import type { MeloData } from "./types";
import { PLANS } from "./billing";
import { DEFAULT_INVOICE_TEMPLATES } from "./invoice-templates";
import { DEFAULT_GRANTS, NATIVE_MCP } from "./agent-tools";

const T0 = "2026-09-03T08:12:00+10:00";
const WED = "2026-09-02";
const THU = "2026-09-03";
const FRI = "2026-09-04";

export function createSeed(): MeloData {
  return {
    workspace: {
      name: "Northside Plumbing",
      industry: "trades",
      ownerName: "Alex",
      ownerEmail: "alex@northsideplumbing.com.au",
      number: "+61 2 5550 1840",
      timezone: "Australia/Sydney",
      abn: "51 824 753 556",
      address: "12 Parramatta Rd, Annandale NSW 2038",
      brandName: "Northside Plumbing",
      brandPrimary: "#2B7FFF",
      widgetGreeting: "Hi — Northside Plumbing here. Blocked drain, leak or hot water? I can quote or book a tech.",
    },
    staff: [
      {
        id: "alex",
        name: "Alex Chen",
        role: "Owner",
        email: "alex@northsideplumbing.com.au",
        phone: "+61 412 001 840",
        color: "primary",
        skills: ["quoting", "gas"],
      },
      {
        id: "sam",
        name: "Sam Okonkwo",
        role: "Technician",
        email: "sam@northsideplumbing.com.au",
        phone: "+61 413 220 118",
        color: "primary",
        skills: ["drains", "leaks", "hot water"],
      },
      {
        id: "dez",
        name: "Dez Walker",
        role: "Technician",
        email: "dez@northsideplumbing.com.au",
        phone: "+61 414 880 442",
        color: "agent-dispatch",
        skills: ["blocked drains", "jetting", "cameras"],
      },
    ],
    customers: [
      {
        id: "mia",
        name: "Mia Thompson",
        phone: "+61 412 880 214",
        email: "mia.thompson@gmail.com",
        sites: [
          {
            id: "mia-home",
            label: "Home",
            address: "14 King St",
            suburb: "Newtown",
            state: "NSW",
            postcode: "2042",
          },
        ],
        tags: ["WhatsApp", "Inner West"],
        since: "2025-11-04",
        notes: "Prefers morning windows. Laundry is under the house — tight access.",
      },
      {
        id: "james",
        name: "James Wilson",
        phone: "+61 400 118 903",
        email: "j.wilson@outlook.com",
        sites: [
          {
            id: "james-home",
            label: "Home",
            address: "8 Victoria St",
            suburb: "Burwood",
            state: "NSW",
            postcode: "2134",
          },
        ],
        tags: ["Voice", "After-hours"],
        since: "2026-03-12",
        notes: "Older terracotta line. Has had two blockages this year.",
      },
      {
        id: "priya",
        name: "Priya Nair",
        phone: "+61 419 332 710",
        email: "priya.nair@me.com",
        sites: [
          {
            id: "priya-home",
            label: "Unit",
            address: "3/44 Hall St",
            suburb: "Bondi",
            state: "NSW",
            postcode: "2026",
          },
        ],
        tags: ["SMS"],
        since: "2024-08-20",
        notes: "Strata — needs photos for the OC.",
      },
      {
        id: "tom",
        name: "Tom Brennan",
        phone: "+61 422 091 445",
        email: "tombrennan@fastmail.com",
        sites: [
          {
            id: "tom-home",
            label: "Home",
            address: "27 Illawarra Rd",
            suburb: "Marrickville",
            state: "NSW",
            postcode: "2204",
          },
        ],
        tags: ["After-hours"],
        since: "2026-01-08",
        notes: "Called twice overnight. Callback promised.",
      },
      {
        id: "helen",
        name: "Helen Cho",
        phone: "+61 431 667 209",
        email: "helen.cho@artarmon.legal",
        company: "Cho & Partners",
        sites: [
          {
            id: "helen-office",
            label: "Office",
            address: "201 Pacific Hwy",
            suburb: "Artarmon",
            state: "NSW",
            postcode: "2064",
          },
        ],
        tags: ["Email", "Commercial"],
        since: "2023-05-14",
        notes: "Accounts payable wants Xero invoices.",
      },
      {
        id: "ravi",
        name: "Ravi Patel",
        phone: "+61 415 772 003",
        email: "ravi@patel.family",
        sites: [
          {
            id: "ravi-home",
            label: "Home",
            address: "9 Liberty St",
            suburb: "Enmore",
            state: "NSW",
            postcode: "2042",
          },
        ],
        tags: ["Instagram"],
        since: "2026-07-02",
        notes: "Found us on Instagram. Tap leak.",
      },
      {
        id: "visitor",
        name: "Website visitor",
        phone: "",
        email: "",
        sites: [
          {
            id: "visitor-newtown",
            label: "Newtown",
            address: "",
            suburb: "Newtown",
            state: "NSW",
            postcode: "2042",
          },
        ],
        tags: ["Widget"],
        since: THU,
        notes: "",
      },
    ],
    agents: [
      {
        id: "receptionist",
        name: "Receptionist",
        role: "Front desk",
        blurb: "Answers calls and chat, books windows, and triages emergencies.",
        portrait: "/agents/receptionist.jpg",
        color: "agent-receptionist",
        status: "working",
        currentTask: "On a live call with James Wilson",
        tools: ["Voice", "Chat", "Calendar", "Knowledge"],
        permissions: ["read", "draft", "write", "call"],
        autopilot: "act",
        voice: "Australian English · Isla",
        taskCount: 6,
        handlesCalls: true,
        hired: true,
        integrationIds: DEFAULT_GRANTS.receptionist.apps,
        mcpIds: DEFAULT_GRANTS.receptionist.mcp,
      },
      {
        id: "dispatch",
        name: "Dispatch",
        role: "Jobs board",
        blurb: "Keeps the board honest — travel windows, load and who is actually free.",
        portrait: "/agents/dispatch.jpg",
        color: "agent-dispatch",
        status: "working",
        currentTask: "Balancing Thursday Inner West run",
        tools: ["Calendar", "Jobs", "Maps"],
        permissions: ["read", "draft", "write"],
        autopilot: "act",
        taskCount: 4,
        handlesCalls: false,
        hired: true,
        integrationIds: DEFAULT_GRANTS.dispatch.apps,
        mcpIds: DEFAULT_GRANTS.dispatch.mcp,
      },
      {
        id: "scout",
        name: "Scout",
        role: "Leads",
        blurb: "New leads, quote follow-up, missed-call recovery and no-show chase.",
        portrait: "/agents/scout.jpg",
        color: "agent-scout",
        status: "working",
        currentTask: "Following up 3 quiet quotes",
        tools: ["Inbox", "Sequences", "GBP"],
        permissions: ["read", "draft"],
        autopilot: "draft",
        taskCount: 8,
        handlesCalls: true,
        hired: true,
        integrationIds: DEFAULT_GRANTS.scout.apps,
        mcpIds: DEFAULT_GRANTS.scout.mcp,
      },
      {
        id: "quill",
        name: "Quill",
        role: "Content",
        blurb: "Service pages, blogs and Google Business Profile posts from real demand.",
        portrait: "/agents/quill.jpg",
        color: "agent-quill",
        status: "waiting",
        currentTask: "GBP post in Review",
        tools: ["Knowledge", "GBP", "CMS"],
        permissions: ["read", "draft"],
        autopilot: "draft",
        taskCount: 3,
        handlesCalls: false,
        hired: true,
        integrationIds: DEFAULT_GRANTS.quill.apps,
        mcpIds: DEFAULT_GRANTS.quill.mcp,
      },
      {
        id: "ledger",
        name: "Ledger",
        role: "Money",
        blurb: "Quotes, invoices, deposits, payments and overdue accounts.",
        portrait: "/agents/ledger.jpg",
        color: "agent-ledger",
        status: "waiting",
        currentTask: "Quote Q-2041 waiting on Alex",
        tools: ["Quotes", "Invoices", "Xero", "Stripe"],
        permissions: ["read", "draft"],
        autopilot: "ask",
        taskCount: 5,
        handlesCalls: false,
        hired: true,
        integrationIds: DEFAULT_GRANTS.ledger.apps,
        mcpIds: DEFAULT_GRANTS.ledger.mcp,
      },
      {
        id: "brief",
        name: "Brief",
        role: "Research",
        blurb: "Competitors, tenders and overnight research, filed for the morning.",
        portrait: "/agents/brief.jpg",
        color: "agent-brief",
        status: "idle",
        currentTask: null,
        tools: ["Research", "Tenders"],
        permissions: ["read", "draft"],
        autopilot: "draft",
        taskCount: 1,
        handlesCalls: false,
        hired: true,
        integrationIds: DEFAULT_GRANTS.brief.apps,
        mcpIds: DEFAULT_GRANTS.brief.mcp,
      },
      {
        id: "helix",
        name: "Helix",
        role: "Floor manager",
        blurb: "Orchestrates the firm. Speaks through Ask Melo, assigns work in parallel, logs every action.",
        portrait: "/agents/helix.jpg",
        color: "agent-helix",
        status: "working",
        currentTask: "Running the morning brief",
        tools: ["Ask Melo", "Review", "Activity"],
        permissions: ["read", "draft", "write"],
        autopilot: "act",
        taskCount: 11,
        handlesCalls: false,
        hired: true,
        integrationIds: DEFAULT_GRANTS.helix.apps,
        mcpIds: DEFAULT_GRANTS.helix.mcp,
      },
    ],
    marketplace: [
      {
        id: "estimator",
        name: "Plumbing Estimator",
        role: "Take-offs",
        blurb: "Builds priced scopes from photos, job notes and the price book.",
        portrait: "/agents/estimator.jpg",
        color: "agent-brief",
        tools: ["Price book", "Quotes", "Photos"],
        handlesCalls: false,
        preview: "Using Northside’s price book, Estimator would price Mia Thompson’s laundry leak at A$420 inc GST (call-out, 1.5 hrs labour, waste fittings) and send it to Review.",
        pack: "Trades pack",
      },
      {
        id: "gbp",
        name: "GBP Manager",
        role: "Listings",
        blurb: "Keeps Google Business Profile posts, photos and Q&A in lockstep with jobs.",
        portrait: "/agents/gbp.jpg",
        color: "agent-ledger",
        tools: ["GBP", "Photos", "Reviews"],
        handlesCalls: false,
        preview: "Would schedule a Burwood hot-water post this week off three real calls, and reply to yesterday’s 5-star review in Alex’s voice.",
        pack: "Reach pack",
      },
      {
        id: "review-chaser",
        name: "Review Chaser",
        role: "Reputation",
        blurb: "Asks happy customers for Google reviews at the right moment — never after a complaint.",
        portrait: "/agents/review-chaser.jpg",
        color: "agent-scout",
        tools: ["Inbox", "GBP", "Jobs"],
        handlesCalls: true,
        preview: "Would text Priya Nair tomorrow after the Bondi hot-water job is marked Won, using the SMS template in Knowledge.",
        pack: "Reach pack",
      },
      {
        id: "hospitality",
        name: "Hospitality Host",
        role: "Reservations",
        blurb: "Takes bookings, allergen notes and waitlist moves for venues.",
        portrait: "/agents/hospitality.jpg",
        color: "agent-dispatch",
        tools: ["Voice", "Calendar", "SMS"],
        handlesCalls: true,
        preview: "In a hospitality workspace this agent answers reservation calls. In Northside it stays idle until industry is switched.",
        pack: "Hospitality pack",
      },
      {
        id: "triage",
        name: "After-hours Triage",
        role: "Night desk",
        blurb: "A second receptionist trained on emergency vs morning-callback rules.",
        portrait: "/agents/triage.jpg",
        color: "agent-helix",
        tools: ["Voice", "Knowledge", "Dispatch"],
        handlesCalls: true,
        preview: "Would have booked Tom Brennan’s Marrickville overflow last night instead of leaving a callback, using the after-hours price in Knowledge.",
        pack: "Voice pack",
      },
      {
        id: "clinic",
        name: "Clinic Intake",
        role: "Intake",
        blurb: "New-patient forms, Medicare notes and appointment triage for clinics.",
        portrait: "/agents/clinic.jpg",
        color: "agent-receptionist",
        tools: ["Voice", "Calendar", "Forms"],
        handlesCalls: true,
        preview: "Built for clinics. Switch industry to Clinics & allied health to preview intake language on the same data model.",
        pack: "Clinics pack",
      },
    ],
    conversations: [
      {
        id: "conv-mia",
        customerId: "mia",
        channel: "whatsapp",
        subject: "Laundry leak — Newtown",
        preview: "Thursday 7:30 am with Sam still works for me",
        updatedAt: "2026-09-03T07:48:00+10:00",
        unread: 0,
        assignedAgentId: "receptionist",
        jobId: "job-1041",
        messages: [
          {
            id: "m1",
            at: "2026-09-02T21:14:00+10:00",
            from: "customer",
            author: "Mia Thompson",
            text: "Hi — water is coming through the ceiling under the laundry. Newtown. Can someone come?",
            channel: "whatsapp",
          },
          {
            id: "m2",
            at: "2026-09-02T21:14:40+10:00",
            from: "agent",
            author: "Receptionist",
            text: "Hi Mia, I’m the Northside Plumbing receptionist. Sorry about the leak. Is it still running, and is it safe to switch the laundry tap off at the wall?",
            channel: "whatsapp",
          },
          {
            id: "m3",
            at: "2026-09-02T21:16:00+10:00",
            from: "customer",
            author: "Mia Thompson",
            text: "Taps off. It’s a slow drip now but the ceiling is wet. After hours?",
            channel: "whatsapp",
          },
          {
            id: "m4",
            at: "2026-09-02T21:17:10+10:00",
            from: "agent",
            author: "Receptionist",
            text: "We can attend after hours from A$280, or first thing Thursday. Sam has 7:30 am. I’ll send a quote either way — typical laundry leak is A$420 inc GST if we catch it without opening the floor.",
            channel: "whatsapp",
          },
          {
            id: "m5",
            at: "2026-09-02T21:20:00+10:00",
            from: "agent",
            author: "Ledger",
            text: "Quote Q-2041 is ready for Alex in Review (A$420 inc GST). I have not sent it to Mia yet.",
            channel: "whatsapp",
          },
          {
            id: "m6",
            at: "2026-09-03T07:48:00+10:00",
            from: "customer",
            author: "Mia Thompson",
            text: "Thursday 7:30 am with Sam still works for me if you can send the quote.",
            channel: "whatsapp",
          },
        ],
      },
      {
        id: "conv-james",
        customerId: "james",
        channel: "voice",
        subject: "Blocked drain — Burwood",
        preview: "Live · downstairs toilet backing up",
        updatedAt: T0,
        unread: 1,
        assignedAgentId: "receptionist",
        jobId: "job-1042",
        messages: [
          {
            id: "j1",
            at: "2026-09-03T08:04:00+10:00",
            from: "customer",
            author: "James Wilson",
            text: "Downstairs toilet is backing up — Victoria St, Burwood. Can you get someone today?",
            channel: "voice",
          },
          {
            id: "j2",
            at: "2026-09-03T08:05:00+10:00",
            from: "agent",
            author: "Receptionist",
            text: "Yes James. Dez is on a Burwood run and has 10:00 am. I’ll hold that window. Is anyone else in the house using water?",
            channel: "voice",
          },
        ],
      },
      {
        id: "conv-tom",
        customerId: "tom",
        channel: "voice",
        subject: "Overflow — Marrickville",
        preview: "After-hours · promised a morning callback",
        updatedAt: "2026-09-02T23:44:00+10:00",
        unread: 1,
        assignedAgentId: "receptionist",
        messages: [
          {
            id: "t1",
            at: "2026-09-02T23:41:00+10:00",
            from: "customer",
            author: "Tom Brennan",
            text: "Gully trap overflowing onto the neighbour’s side. Illawarra Rd.",
            channel: "voice",
          },
          {
            id: "t2",
            at: "2026-09-02T23:42:00+10:00",
            from: "agent",
            author: "Receptionist",
            text: "Logged as after-hours. Both techs are off shift. I can send someone now from A$280 or Alex will call you at 7:30 am. Which do you prefer?",
            channel: "voice",
          },
          {
            id: "t3",
            at: "2026-09-02T23:43:00+10:00",
            from: "customer",
            author: "Tom Brennan",
            text: "Morning is fine if it’s first call. Please actually call.",
            channel: "voice",
          },
        ],
      },
      {
        id: "conv-priya",
        customerId: "priya",
        channel: "sms",
        subject: "Hot water — Bondi",
        preview: "Confirmed 2:00 pm with Sam",
        updatedAt: "2026-09-03T07:10:00+10:00",
        unread: 0,
        assignedAgentId: "dispatch",
        jobId: "job-1043",
        messages: [
          {
            id: "p1",
            at: "2026-09-02T16:40:00+10:00",
            from: "customer",
            author: "Priya Nair",
            text: "No hot water in the unit since last night. Hall St Bondi. Strata wants photos.",
            channel: "sms",
          },
          {
            id: "p2",
            at: "2026-09-02T16:41:00+10:00",
            from: "agent",
            author: "Receptionist",
            text: "Booked Sam Thursday 2:00 pm. We’ll photograph the unit and the heater for the OC. Typical repair from A$220 inc GST.",
            channel: "sms",
          },
        ],
      },
      {
        id: "conv-helen",
        customerId: "helen",
        channel: "email",
        subject: "Quote follow-up — Artarmon amenities",
        preview: "Can you keep the original scope and just extend labour?",
        updatedAt: "2026-09-03T06:55:00+10:00",
        unread: 1,
        assignedAgentId: "scout",
        jobId: "job-1045",
        messages: [
          {
            id: "h1",
            at: "2026-09-01T11:02:00+10:00",
            from: "agent",
            author: "Scout",
            text: "Helen — circling back on the amenities rough-in quote (A$6,400). Happy to hold pricing until Friday.",
            channel: "email",
          },
          {
            id: "h2",
            at: "2026-09-03T06:55:00+10:00",
            from: "customer",
            author: "Helen Cho",
            text: "Please keep the original scope and add a half-day labour. Accounts still need this in Xero.",
            channel: "email",
          },
        ],
      },
      {
        id: "conv-ravi",
        customerId: "ravi",
        channel: "instagram",
        subject: "Tap leak — Enmore",
        preview: "Sent a photo of the mixer",
        updatedAt: "2026-09-02T19:12:00+10:00",
        unread: 1,
        assignedAgentId: "scout",
        jobId: "job-1046",
        messages: [
          {
            id: "r1",
            at: "2026-09-02T19:10:00+10:00",
            from: "customer",
            author: "Ravi Patel",
            text: "Saw your drain post. Kitchen mixer is dripping — Enmore. Photo attached.",
            channel: "instagram",
          },
          {
            id: "r2",
            at: "2026-09-02T19:12:00+10:00",
            from: "agent",
            author: "Scout",
            text: "Got the photo. Looks like a cartridge. I can have someone Friday morning — draft quote is in Review.",
            channel: "instagram",
          },
        ],
      },
      {
        id: "conv-missed",
        customerId: "tom",
        channel: "voice",
        subject: "Missed call · +61 422 091 445",
        preview: "Second after-hours attempt 10:03 pm",
        updatedAt: "2026-09-02T22:03:00+10:00",
        unread: 1,
        assignedAgentId: "scout",
        messages: [
          {
            id: "mc1",
            at: "2026-09-02T22:03:00+10:00",
            from: "system",
            author: "Receptionist",
            text: "Missed after-hours call from Tom Brennan. Scout enrolled him in missed-call recovery.",
            channel: "voice",
          },
        ],
      },
    ],
    jobs: [
      {
        id: "job-1041",
        number: "JOB-1041",
        title: "Laundry leak",
        stage: "quoted",
        customerId: "mia",
        siteId: "mia-home",
        suburb: "Newtown",
        value: 420,
        assigneeId: "sam",
        nextAction: "Approve quote Q-2041 and book Thu 7:30 am",
        channel: "whatsapp",
        scheduledStart: "2026-09-03T07:30:00+10:00",
        scheduledEnd: "2026-09-03T09:00:00+10:00",
        travelMins: 25,
        workOrder: "WO-7712",
        scope: "Trace and repair laundry leak under the house. No floor demolition unless the copper has pinholed.",
        items: [
          { id: "li1", kind: "callout", description: "After-hours / priority call-out", qty: 1, unit: "ea", cost: 0, sell: 90 },
          { id: "li2", kind: "labour", description: "Labour — leak trace and repair", qty: 1.5, unit: "hr", cost: 55, sell: 140 },
          { id: "li3", kind: "material", description: "Materials — waste fittings & sealant", qty: 1, unit: "lot", cost: 32, sell: 81.82 },
        ],
        labour: [],
        quote: {
          id: "q-2041",
          number: "Q-2041",
          status: "in_review",
          issuedAt: "2026-09-02T21:18:00+10:00",
          expiry: "2026-09-16",
          terms: "Valid 14 days. GST included in total. Deposit not required under A$1,000.",
          depositPct: 0,
          discount: 0,
          items: [
            { id: "li1", kind: "callout", description: "After-hours / priority call-out", qty: 1, unit: "ea", cost: 0, sell: 90 },
            { id: "li2", kind: "labour", description: "Labour — leak trace and repair", qty: 1.5, unit: "hr", cost: 55, sell: 140 },
            { id: "li3", kind: "material", description: "Materials — waste fittings & sealant", qty: 1, unit: "lot", cost: 32, sell: 81.82 },
          ],
        },
        invoices: [],
        payments: [],
        notes: [
          {
            id: "n1",
            at: "2026-09-02T21:19:00+10:00",
            author: "Ledger",
            text: "Quote prepared from price book + after-hours WhatsApp. Awaiting Alex in Review.",
          },
        ],
        attachments: [{ id: "a1", name: "laundry-ceiling.jpg", kind: "photo" }],
        statusHistory: [
          { at: "2026-09-02T21:14:00+10:00", stage: "new", note: "WhatsApp lead" },
          { at: "2026-09-02T21:18:00+10:00", stage: "quoted", note: "Q-2041 drafted" },
        ],
      },
      {
        id: "job-1042",
        number: "JOB-1042",
        title: "Blocked drain",
        stage: "booked",
        customerId: "james",
        siteId: "james-home",
        suburb: "Burwood",
        value: 280,
        assigneeId: "dez",
        nextAction: "Dez on site 10:00 am · jet + camera",
        channel: "voice",
        scheduledStart: "2026-09-03T10:00:00+10:00",
        scheduledEnd: "2026-09-03T11:30:00+10:00",
        travelMins: 20,
        workOrder: "WO-7713",
        scope: "Clear downstairs toilet backup. Camera the line if it is the terracotta again.",
        items: [
          { id: "b1", kind: "callout", description: "Call-out", qty: 1, unit: "ea", cost: 0, sell: 90 },
          { id: "b2", kind: "labour", description: "Jetting and camera", qty: 1, unit: "hr", cost: 55, sell: 172.73 },
        ],
        labour: [],
        invoices: [],
        payments: [],
        notes: [],
        attachments: [],
        statusHistory: [
          { at: "2026-09-03T08:04:00+10:00", stage: "new", note: "Inbound call" },
          { at: "2026-09-03T08:08:00+10:00", stage: "booked", note: "Dez 10:00 am" },
        ],
      },
      {
        id: "job-1043",
        number: "JOB-1043",
        title: "Hot water repair",
        stage: "booked",
        customerId: "priya",
        siteId: "priya-home",
        suburb: "Bondi",
        value: 360,
        assigneeId: "sam",
        nextAction: "Sam 2:00 pm · photos for OC",
        channel: "sms",
        scheduledStart: "2026-09-03T14:00:00+10:00",
        scheduledEnd: "2026-09-03T15:30:00+10:00",
        travelMins: 35,
        workOrder: "WO-7714",
        scope: "Diagnose no hot water. Photograph unit and heater for strata.",
        items: [
          { id: "hwi", kind: "labour", description: "Diagnosis and repair", qty: 1.5, unit: "hr", cost: 55, sell: 200 },
          { id: "hwi2", kind: "material", description: "Thermostat / parts allowance", qty: 1, unit: "ea", cost: 48, sell: 127.27 },
        ],
        labour: [],
        invoices: [],
        payments: [],
        notes: [],
        attachments: [],
        statusHistory: [
          { at: "2026-09-02T16:40:00+10:00", stage: "new", note: "SMS" },
          { at: "2026-09-02T16:41:00+10:00", stage: "booked", note: "Sam 2:00 pm" },
        ],
      },
      {
        id: "job-1044",
        number: "JOB-1044",
        title: "Gully overflow",
        stage: "new",
        customerId: "tom",
        siteId: "tom-home",
        suburb: "Marrickville",
        value: 280,
        assigneeId: null,
        nextAction: "Callback 7:30 am as promised",
        channel: "voice",
        travelMins: 20,
        scope: "After-hours overflow on neighbour’s side. Morning first call.",
        items: [],
        labour: [],
        invoices: [],
        payments: [],
        notes: [],
        attachments: [],
        statusHistory: [{ at: "2026-09-02T23:41:00+10:00", stage: "new", note: "After-hours call" }],
      },
      {
        id: "job-1045",
        number: "JOB-1045",
        title: "Amenities rough-in",
        stage: "quoted",
        customerId: "helen",
        siteId: "helen-office",
        suburb: "Artarmon",
        value: 6400,
        assigneeId: "alex",
        nextAction: "Revise labour and resend",
        channel: "email",
        workOrder: "WO-7688",
        scope: "Commercial amenities rough-in, two pans, one basin, one cleaners sink.",
        items: [
          { id: "c1", kind: "labour", description: "Rough-in labour", qty: 16, unit: "hr", cost: 55, sell: 140 },
          { id: "c2", kind: "material", description: "Pipe, fixtures allowance", qty: 1, unit: "lot", cost: 2100, sell: 3781.82 },
        ],
        labour: [],
        quote: {
          id: "q-2033",
          number: "Q-2033",
          status: "sent",
          issuedAt: "2026-08-28T09:00:00+10:00",
          expiry: "2026-09-11",
          terms: "50% deposit on acceptance. Balance on completion. GST extra on this commercial quote.",
          depositPct: 50,
          discount: 0,
          items: [
            { id: "c1", kind: "labour", description: "Rough-in labour", qty: 16, unit: "hr", cost: 55, sell: 140 },
            { id: "c2", kind: "material", description: "Pipe, fixtures allowance", qty: 1, unit: "lot", cost: 2100, sell: 3781.82 },
          ],
          sentAt: "2026-08-28T09:12:00+10:00",
          signature: {
            status: "awaiting",
            sentAt: "2026-08-28T09:12:00+10:00",
            sentChannel: "email",
          },
        },
        invoices: [
          {
            id: "inv-3199",
            number: "INV-3199",
            kind: "deposit",
            status: "awaiting_approval",
            issuedAt: "2026-09-03T07:02:00+10:00",
            dueAt: "2026-09-10",
            items: [
              {
                id: "dep-2033",
                kind: "other",
                description: "50% deposit on Q-2033",
                qty: 1,
                unit: "ea",
                cost: 0,
                sell: 2909.09,
              },
            ],
            discount: 0,
            xeroSync: "pending",
          },
        ],
        payments: [],
        notes: [],
        attachments: [{ id: "a2", name: "artarmon-plan.pdf", kind: "pdf" }],
        statusHistory: [
          { at: "2026-08-26T10:00:00+10:00", stage: "new", note: "Email enquiry" },
          { at: "2026-08-28T09:12:00+10:00", stage: "quoted", note: "Q-2033 sent" },
        ],
      },
      {
        id: "job-1046",
        number: "JOB-1046",
        title: "Kitchen mixer drip",
        stage: "new",
        customerId: "ravi",
        siteId: "ravi-home",
        suburb: "Enmore",
        value: 180,
        assigneeId: null,
        nextAction: "Approve Scout’s reply and offer Friday",
        channel: "instagram",
        scope: "Replace mixer cartridge from Instagram photo.",
        items: [
          { id: "k1", kind: "labour", description: "Cartridge replacement", qty: 0.75, unit: "hr", cost: 55, sell: 140 },
          { id: "k2", kind: "material", description: "Cartridge", qty: 1, unit: "ea", cost: 28, sell: 75 },
        ],
        labour: [],
        invoices: [],
        payments: [],
        notes: [],
        attachments: [{ id: "a3", name: "mixer.jpg", kind: "photo" }],
        statusHistory: [{ at: "2026-09-02T19:10:00+10:00", stage: "new", note: "Instagram" }],
      },
      {
        id: "job-1040",
        number: "JOB-1040",
        title: "Water filter install",
        stage: "on_site",
        customerId: "helen",
        siteId: "helen-office",
        suburb: "Artarmon",
        value: 890,
        assigneeId: "dez",
        nextAction: "Dez finishing on site",
        channel: "email",
        scheduledStart: "2026-09-03T08:00:00+10:00",
        scheduledEnd: "2026-09-03T09:30:00+10:00",
        travelMins: 20,
        workOrder: "WO-7709",
        scope: "Under-sink filter on the staff kitchen.",
        items: [
          { id: "f1", kind: "labour", description: "Install", qty: 1.5, unit: "hr", cost: 55, sell: 140 },
          { id: "f2", kind: "material", description: "Filter kit", qty: 1, unit: "ea", cost: 210, sell: 618.18 },
        ],
        labour: [{ id: "lb1", staffId: "dez", date: THU, hours: 1.2, rateCost: 55, note: "On site" }],
        invoices: [
          {
            id: "inv-3204",
            number: "INV-3204",
            kind: "final",
            status: "draft",
            issuedAt: "2026-09-03T09:10:00+10:00",
            dueAt: "2026-09-17",
            items: [
              { id: "f1i", kind: "labour", description: "Install", qty: 1.5, unit: "hr", cost: 55, sell: 140 },
              { id: "f2i", kind: "material", description: "Filter kit", qty: 1, unit: "ea", cost: 210, sell: 618.18 },
            ],
            discount: 0,
            xeroSync: "pending",
          },
        ],
        payments: [],
        notes: [],
        attachments: [],
        statusHistory: [
          { at: "2026-08-30T09:00:00+10:00", stage: "new", note: "Email" },
          { at: "2026-09-01T11:00:00+10:00", stage: "booked", note: "Thu 8:00" },
          { at: "2026-09-03T08:05:00+10:00", stage: "on_site", note: "Dez arrived" },
        ],
      },
      {
        id: "job-1031",
        number: "JOB-1031",
        title: "Hot water replacement",
        stage: "won",
        customerId: "priya",
        siteId: "priya-home",
        suburb: "Bondi",
        value: 2140,
        assigneeId: "sam",
        nextAction: "Review request Friday",
        channel: "sms",
        workOrder: "WO-7650",
        scope: "50L replacement, completed last month.",
        items: [
          { id: "w1", kind: "labour", description: "Replace and commission", qty: 3, unit: "hr", cost: 55, sell: 140 },
          { id: "w2", kind: "material", description: "50L electric HWS", qty: 1, unit: "ea", cost: 980, sell: 1563.64 },
        ],
        labour: [{ id: "lb2", staffId: "sam", date: "2026-08-12", hours: 3, rateCost: 55, note: "Completed" }],
        invoices: [
          {
            id: "inv-3102",
            number: "INV-3102",
            kind: "final",
            status: "paid",
            issuedAt: "2026-08-12T16:00:00+10:00",
            dueAt: "2026-08-26",
            items: [
              { id: "w1", kind: "labour", description: "Replace and commission", qty: 3, unit: "hr", cost: 55, sell: 140 },
              { id: "w2", kind: "material", description: "50L electric HWS", qty: 1, unit: "ea", cost: 980, sell: 1563.64 },
            ],
            discount: 0,
            xeroSync: "synced",
            viewedAt: "2026-08-13T09:00:00+10:00",
          },
        ],
        payments: [
          {
            id: "pay1",
            invoiceId: "inv-3102",
            at: "2026-08-14T10:12:00+10:00",
            amount: 2182,
            method: "stripe",
            note: "Paid via link",
          },
        ],
        notes: [],
        attachments: [],
        statusHistory: [
          { at: "2026-08-10T09:00:00+10:00", stage: "new", note: "SMS" },
          { at: "2026-08-12T16:10:00+10:00", stage: "won", note: "Paid INV-3102" },
        ],
      },
    ],
    holds: [
      { id: "tr1", staffId: "sam", start: "2026-09-03T07:05:00+10:00", end: "2026-09-03T07:30:00+10:00", kind: "travel", label: "To Newtown" },
      { id: "tr2", staffId: "dez", start: "2026-09-03T09:40:00+10:00", end: "2026-09-03T10:00:00+10:00", kind: "travel", label: "Artarmon → Burwood" },
      { id: "tr3", staffId: "sam", start: "2026-09-03T13:25:00+10:00", end: "2026-09-03T14:00:00+10:00", kind: "travel", label: "To Bondi" },
    ],
    knowledge: {
      sources: [
        { id: "website", name: "northsideplumbing.com.au", kind: "website", status: "synced", updatedAt: "2026-09-01T08:00:00+10:00", coverage: 92 },
        { id: "price-book", name: "Price book 2026", kind: "price_book", status: "synced", updatedAt: "2026-08-20T09:00:00+10:00", coverage: 88 },
        { id: "job-system", name: "Job history", kind: "job_system", status: "synced", updatedAt: T0, coverage: 80 },
        { id: "transcripts", name: "Call transcripts", kind: "transcripts", status: "syncing", updatedAt: T0, coverage: 74 },
        { id: "booking-rules", name: "Booking rules", kind: "manual", status: "synced", updatedAt: "2026-08-02T10:00:00+10:00", coverage: 95 },
      ],
      services: [
        { id: "blocked-drain", name: "Blocked drains", summary: "Toilets, gully traps and main lines. Jetting and camera available.", priceFrom: 180, afterHoursFrom: 280, durationMins: 75, active: true },
        { id: "leak", name: "Leak detection & repair", summary: "Ceiling, laundry and under-house leaks.", priceFrom: 180, afterHoursFrom: 280, durationMins: 90, active: true },
        { id: "hot-water", name: "Hot water repairs", summary: "Electric and gas. Replacement quoted separately.", priceFrom: 220, afterHoursFrom: 320, durationMins: 90, active: true },
        { id: "emergency", name: "Emergency plumbing", summary: "Overflows, bursts and no-water events.", priceFrom: 280, afterHoursFrom: 280, durationMins: 90, active: true },
        { id: "gas", name: "Gas fitting", summary: "Licensed gas. Cooktops, heaters, compliance.", priceFrom: 240, afterHoursFrom: 340, durationMins: 120, active: true },
      ],
      areas: ["Newtown", "Marrickville", "Enmore", "Burwood", "Bondi", "Inner West", "Annandale", "Glebe"],
      faqs: [
        { id: "f1", q: "Do you service Newtown?", a: "Yes — Newtown is a core suburb. Same-day morning windows are common.", sourceId: "website" },
        { id: "f2", q: "Are you licensed?", a: "Yes. NSW licensed plumbers and gasfitters. Licence details are on the website footer and can be read on the call.", sourceId: "website" },
        { id: "f3", q: "Do you work after hours?", a: "Yes. After-hours emergency attendance is available. Pricing is higher than the daytime book.", sourceId: "booking-rules" },
      ],
      hours: "Workshop hours Monday to Friday 7:00 am – 5:00 pm Sydney time. Saturday by arrangement. Sunday emergency only.",
      afterHours: "After hours is 5:00 pm – 7:00 am weekdays, and all weekend. We attend genuine emergencies; otherwise we book first window next morning.",
      bookingRules: "Standard jobs book in 90-minute windows. Travel buffer 20–35 minutes depending on suburb. Sam prefers Inner West mornings; Dez covers Burwood / west. Bondi is afternoon unless emergency. Do not double-book a tech without a 30-minute travel hold.",
      greeting: "Northside Plumbing, this is the receptionist.",
    },
    reviewItems: [
      {
        id: "rev-q2041",
        kind: "quote",
        title: "Quote Q-2041 · Mia Thompson",
        summary: "Laundry leak Newtown · A$420 inc GST · Thu 7:30 am hold",
        agentId: "ledger",
        status: "pending",
        createdAt: "2026-09-02T21:18:00+10:00",
        sources: ["Price book 2026", "WhatsApp transcript"],
        preview: "Call-out $90 + labour 1.5 hrs + materials. Total A$420 including GST. Deposit not required.",
        jobId: "job-1041",
        conversationId: "conv-mia",
        history: [{ at: "2026-09-02T21:18:00+10:00", text: "Ledger drafted from price book." }],
      },
      {
        id: "rev-gbp1",
        kind: "content",
        title: "GBP post · Blocked drains Newtown",
        summary: "Drafted from three real drain calls this week",
        agentId: "quill",
        status: "pending",
        createdAt: "2026-09-03T06:40:00+10:00",
        sources: ["Job history", "GBP"],
        preview: "Same-day blocked drain windows in Newtown this week. Licensed, camera available, after-hours on request.",
        contentId: "c1",
        history: [{ at: "2026-09-03T06:40:00+10:00", text: "Quill drafted. Autopilot is Draft only." }],
      },
      {
        id: "rev-msg1",
        kind: "message",
        title: "Scout reply · Ravi Patel",
        summary: "Instagram mixer drip · offer Friday morning",
        agentId: "scout",
        status: "pending",
        createdAt: "2026-09-02T19:15:00+10:00",
        sources: ["Instagram", "Price book"],
        preview: "Looks like a cartridge — we can do Friday morning in Enmore from A$180 inc GST. Want that window?",
        conversationId: "conv-ravi",
        jobId: "job-1046",
        history: [{ at: "2026-09-02T19:15:00+10:00", text: "Scout drafted. Waiting on Alex." }],
      },
      {
        id: "rev-inv1",
        kind: "money",
        title: "Deposit request · Cho & Partners",
        summary: "50% on Q-2033 if Helen accepts the revised labour",
        agentId: "ledger",
        status: "pending",
        createdAt: "2026-09-03T07:02:00+10:00",
        sources: ["Q-2033", "Xero"],
        preview: "Stripe payment link for A$3,200 deposit, Xero draft invoice attached. Will not send until approved.",
        jobId: "job-1045",
        history: [{ at: "2026-09-03T07:02:00+10:00", text: "Ledger staged. Autopilot is Ask me." }],
      },
    ],
    integrations: [
      { id: "twilio", name: "Twilio", group: "voice", status: "available", detail: "Point your number at Melo" },
      { id: "telnyx", name: "Telnyx", group: "voice", status: "available", detail: "Alternate voice trunk" },
      { id: "gcal", name: "Google Calendar", group: "calendar", status: "connected", detail: "Sam, Dez, Alex calendars" },
      { id: "outlook", name: "Outlook Calendar", group: "calendar", status: "available", detail: "Not connected" },
      { id: "servicem8", name: "ServiceM8", group: "jobs", status: "available", detail: "Field service" },
      { id: "jobber", name: "Jobber", group: "jobs", status: "available", detail: "Field service" },
      { id: "fergus", name: "Fergus", group: "jobs", status: "available", detail: "Trades" },
      { id: "simpro", name: "Simpro", group: "jobs", status: "available", detail: "Job costing" },
      { id: "stripe", name: "Stripe", group: "payments", status: "connected", detail: "Payment links · AU" },
      { id: "square", name: "Square", group: "payments", status: "available", detail: "Card present" },
      { id: "xero", name: "Xero", group: "accounting", status: "connected", detail: "Invoices syncing" },
      { id: "qbo", name: "QuickBooks", group: "accounting", status: "available", detail: "Not connected" },
      { id: "myob", name: "MYOB", group: "accounting", status: "available", detail: "Not connected" },
      { id: "hubspot", name: "HubSpot", group: "crm", status: "available", detail: "CRM" },
      { id: "pipedrive", name: "Pipedrive", group: "crm", status: "available", detail: "CRM" },
      { id: "gmail", name: "Gmail", group: "mail", status: "needs_attention", detail: "Reconnect to read inbound" },
      { id: "olmail", name: "Outlook", group: "mail", status: "available", detail: "Mail" },
      { id: "whatsapp", name: "WhatsApp", group: "social", status: "available", detail: "Business API" },
      { id: "instagram", name: "Instagram", group: "social", status: "available", detail: "DMs" },
      { id: "messenger", name: "Messenger", group: "social", status: "available", detail: "Page DMs" },
      { id: "facebook", name: "Facebook", group: "social", status: "available", detail: "Page" },
      { id: "imessage", name: "iMessage", group: "social", status: "available", detail: "Sendblue or LoopMessage" },
      { id: "wordpress", name: "WordPress", group: "web", status: "available", detail: "CMS" },
      { id: "shopify", name: "Shopify", group: "web", status: "available", detail: "Commerce" },
      { id: "webflow", name: "Webflow", group: "web", status: "available", detail: "CMS" },
      { id: "gbp", name: "Google Business Profile", group: "web", status: "connected", detail: "Northside Plumbing" },
      { id: "slack", name: "Slack", group: "collab", status: "connected", detail: "#jobs · booked alerts" },
      { id: "teams", name: "Teams", group: "collab", status: "available", detail: "Not connected" },
      { id: "zapier", name: "Zapier", group: "collab", status: "connected", detail: "Official · 1 zap on" },
    ],
    automations: [
      { id: "auto-after-hours", name: "After hours", trigger: "Call outside hours", action: "Answer, book if emergency, else morning callback", on: true },
      { id: "auto-missed", name: "Missed call → Scout", trigger: "Missed voice call", action: "SMS + enrol missed-call sequence", on: true },
      { id: "auto-widget", name: "Website chat", trigger: "New widget message", action: "Answer from Knowledge, offer a window", on: true },
      { id: "auto-quote", name: "Quote unsigned 24h", trigger: "Quote sent, not signed", action: "Scout follow-up on the same thread", on: true },
      { id: "auto-slack", name: "Job booked → Slack", trigger: "Job stage becomes Booked", action: "Post to #jobs", on: true },
      { id: "auto-xero", name: "Invoice paid → Xero", trigger: "Payment recorded", action: "Mark invoice paid in Xero", on: true },
    ],
    content: [
      {
        id: "c1",
        title: "Blocked drains Newtown",
        kind: "gbp",
        status: "draft",
        suburb: "Newtown",
        demand: "High · 4 calls this week",
        body: "Same-day blocked drain windows in Newtown this week. Licensed, camera available, after-hours on request.",
        agentId: "quill",
      },
      {
        id: "c2",
        title: "Emergency plumber Marrickville",
        kind: "blog",
        status: "scheduled",
        suburb: "Marrickville",
        demand: "After-hours spike",
        scheduledFor: FRI,
        body: "What counts as a plumbing emergency in Marrickville, what we can do overnight, and how booking first-thing works.",
        agentId: "quill",
      },
      {
        id: "c3",
        title: "Hot water repairs Burwood",
        kind: "service",
        status: "live",
        suburb: "Burwood",
        demand: "Steady",
        body: "Electric and gas hot water repairs across Burwood. Typical diagnosis from A$220 inc GST.",
        agentId: "quill",
      },
      {
        id: "c4",
        title: "Bondi hot water — before/after",
        kind: "gbp",
        status: "gbp",
        suburb: "Bondi",
        demand: "Seasonal",
        body: "Photo post from last month’s 50L replacement (privacy-safe).",
        agentId: "quill",
      },
    ],
    sequences: [
      { id: "seq1", name: "Missed-call recovery", trigger: "Missed voice call", enrolled: 2, active: true, steps: ["SMS in 3 min", "WhatsApp in 20 min", "Owner callback task next morning"] },
      { id: "seq2", name: "Quote follow-up", trigger: "Quote sent, no reply 24h", enrolled: 1, active: true, steps: ["Soft check-in", "Offer a window", "Expire notice"] },
      { id: "seq3", name: "No-show recovery", trigger: "Job marked no-show", enrolled: 0, active: true, steps: ["Sorry SMS", "Rebook link", "Flag Scout"] },
      { id: "seq4", name: "90-day silent customer", trigger: "No job in 90 days", enrolled: 6, active: false, steps: ["Seasonal check-in", "Offer maintenance"] },
    ],
    activity: [
      { id: "ac1", at: T0, actor: "Helix", agentId: "helix", text: "Morning brief compiled — 3 after-hours, 1 booked, 1 callback." },
      { id: "ac2", at: "2026-09-03T08:08:00+10:00", actor: "Receptionist", agentId: "receptionist", text: "Booked Dez 10:00 am for James Wilson · Burwood blocked drain." },
      { id: "ac3", at: "2026-09-03T07:48:00+10:00", actor: "Mia Thompson", text: "Confirmed Thursday 7:30 am on WhatsApp. Quote still in Review." },
      { id: "ac4", at: "2026-09-03T06:40:00+10:00", actor: "Quill", agentId: "quill", text: "Filed GBP draft “Blocked drains Newtown” in Review." },
      { id: "ac5", at: "2026-09-02T23:43:00+10:00", actor: "Receptionist", agentId: "receptionist", text: "After-hours call with Tom Brennan. Callback promised 7:30 am." },
      { id: "ac6", at: "2026-09-02T21:18:00+10:00", actor: "Ledger", agentId: "ledger", text: "Drafted Q-2041 (A$420) for Mia Thompson." },
      { id: "ac7", at: "2026-09-02T16:41:00+10:00", actor: "Dispatch", agentId: "dispatch", text: "Scheduled Sam 2:00 pm Bondi hot water. Travel buffer 35 min." },
    ],
    chat: [
      {
        id: "ch0",
        at: "2026-09-03T07:00:00+10:00",
        role: "melo",
        text: "Morning Alex. Overnight: 3 after-hours calls, 1 booking locked, 1 callback sitting on Tom Brennan. Quote Q-2041 for Mia Thompson is waiting in Review.",
        agentId: "helix",
        chips: [
          { id: "c-ovn", label: "Open overnight brief", action: "run", payload: { run: "overnight" } },
          { id: "c-q", label: "Review Q-2041", action: "open_review", payload: { id: "rev-q2041" } },
        ],
      },
    ],
    notifications: [
      { id: "n1", at: "2026-09-03T07:00:00+10:00", title: "Overnight brief", body: "3 after-hours · 1 booked · 1 callback", href: "/", read: false },
      { id: "n2", at: "2026-09-03T08:04:00+10:00", title: "Live call", body: "James Wilson · Burwood blocked drain", href: "/reception", read: false },
      { id: "n3", at: "2026-09-02T21:18:00+10:00", title: "Quote in Review", body: "Q-2041 Mia Thompson A$420", href: "/review", read: false },
    ],
    voice: {
      locale: "en-AU",
      voice: "Isla",
      warmth: 64,
      pace: 48,
      greeting: "Northside Plumbing, this is the receptionist speaking. How can I help?",
      bargeIn: true,
      transferRules: "Warm-transfer to Alex for billing disputes and anything over A$2,000. Otherwise book and summarise.",
      afterHours: "Offer emergency attendance from the after-hours price, or first morning window. Never leave a customer without a next step.",
    },
    billing: {
      planId: "growth",
      cadence: "monthly",
      renewal: "2026-10-03",
      contact: "alex@northsideplumbing.com.au",
      cancelAt: null,
      trialEndsAt: null,
      card: {
        brand: "visa",
        last4: "4242",
        expMonth: 9,
        expYear: 2028,
        name: "Alex Chen",
      },
      invoices: [
        { id: "sub1", number: "MEL-1044", at: "2026-09-03", exGst: 349, status: "paid" },
        { id: "sub2", number: "MEL-1031", at: "2026-08-03", exGst: 349, status: "paid" },
        { id: "sub3", number: "MEL-1020", at: "2026-07-03", exGst: 349, status: "paid" },
      ],
      addons: [
        { id: "voice-block", name: "Extra voice minutes", on: false, note: "500 minutes when you hit the included cap", priceMonthly: 45 },
        { id: "seat", name: "Additional AI agent seat", on: false, note: "One extra specialist beyond the plan", priceMonthly: 39 },
        { id: "pack-trades", name: "Premium trades pack", on: false, note: "Estimator + after-hours triage", priceMonthly: 89 },
      ],
      apiKeys: [],
      usage: {
        seats: 7,
        voiceMinutes: 412,
        automations: 3,
        teamMembers: 3,
        reset: "2026-10-03",
      },
    },
    plans: PLANS,
    liveCall: {
      id: "call-james",
      customerId: "james",
      from: "+61 400 118 903",
      suburb: "Burwood",
      reason: "Blocked drain · downstairs toilet backing up",
      phase: "live",
      startedAt: "2026-09-03T08:04:00+10:00",
      muted: false,
      recording: true,
      transcript: [
        { at: "2026-09-03T08:04:04+10:00", speaker: "receptionist", text: "Northside Plumbing, receptionist speaking." },
        { at: "2026-09-03T08:04:09+10:00", speaker: "customer", text: "G’day — James Wilson, Victoria Street Burwood. The downstairs toilet is backing up." },
        { at: "2026-09-03T08:04:18+10:00", speaker: "receptionist", text: "Sorry to hear that James. Is it overflowing now, or sitting high?" },
        { at: "2026-09-03T08:04:24+10:00", speaker: "customer", text: "Sitting high. We stopped using water. Happened once in March." },
        { at: "2026-09-03T08:04:32+10:00", speaker: "receptionist", text: "Dez is already on a Burwood run. He has 10:00 am. I can hold that window — about ninety minutes on site if we camera the line." },
        { at: "2026-09-03T08:04:44+10:00", speaker: "customer", text: "Ten is good. Do I need to be home?" },
        { at: "2026-09-03T08:04:50+10:00", speaker: "receptionist", text: "Yes please, or leave access. I’ll text the window and Dez’s first name when we hang up." },
      ],
    },
    recentCalls: [
      {
        id: "call-tom",
        customerId: "tom",
        from: "+61 422 091 445",
        suburb: "Marrickville",
        reason: "Gully overflow",
        phase: "ended",
        startedAt: "2026-09-02T23:41:00+10:00",
        muted: false,
        recording: true,
        summary: "After-hours overflow. Customer declined overnight attendance. Callback promised 7:30 am.",
        transcript: [
          { at: "2026-09-02T23:41:04+10:00", speaker: "receptionist", text: "Northside Plumbing, after hours." },
          { at: "2026-09-02T23:41:10+10:00", speaker: "customer", text: "Gully trap is overflowing onto the neighbour." },
        ],
      },
    ],
    connectors: [],
    mcpServers: NATIVE_MCP,
    invoiceTemplates: DEFAULT_INVOICE_TEMPLATES,
    invoiceSends: [],
    training: {
      website: "https://northsideplumbing.com.au",
      description:
        "Licensed plumbing and gasfitting across the Inner West. Blocked drains, leak detection, hot water, gas and after-hours emergencies. We cover Newtown, Marrickville, Enmore, Burwood, Bondi, Annandale and Glebe. Workshop hours Monday to Friday 7:00 am – 5:00 pm. Same-day windows with a 20–35 minute travel buffer.",
      tools: "Xero, Stripe, Google Calendar, WhatsApp, Slack, Twilio, Google Business Profile",
      runs: [],
    },
  };
}

export const SEED = createSeed();
