/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as HowRouteImport } from './routes/how'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Verify2faRouteImport } from './routes/verify-2fa'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSubsRouteImport } from './routes/admin/subs'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppCalendarRouteImport } from './routes/app/calendar'
import { Route as AppComputerRouteImport } from './routes/app/computer'
import { Route as AppConnectRouteImport } from './routes/app/connect'
import { Route as AppFirmRouteImport } from './routes/app/firm'
import { Route as AppHireRouteImport } from './routes/app/hire'
import { Route as AppInboxRouteImport } from './routes/app/inbox'
import { Route as AppKnowledgeRouteImport } from './routes/app/knowledge'
import { Route as AppPipelineRouteImport } from './routes/app/pipeline'
import { Route as AppReachRouteImport } from './routes/app/reach'
import { Route as AppReceptionRouteImport } from './routes/app/reception'
import { Route as AppReviewRouteImport } from './routes/app/review'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as BookSlugRouteImport } from './routes/book.$slug'
import { Route as PreviewPageRouteImport } from './routes/preview.$page'
import { Route as SignQuoteIdRouteImport } from './routes/sign.$quoteId'
import { Route as WSlugRouteImport } from './routes/w.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiComputerTickRouteImport } from './routes/api/computer/tick'
import { Route as ApiSmsInboundRouteImport } from './routes/api/sms/inbound'
import { Route as ApiVoiceGatherRouteImport } from './routes/api/voice/gather'
import { Route as ApiVoiceHoldRouteImport } from './routes/api/voice/hold'
import { Route as ApiVoiceInboundRouteImport } from './routes/api/voice/inbound'
import { Route as ApiVoiceSampleRouteImport } from './routes/api/voice/sample'
import { Route as ApiVoiceStatusRouteImport } from './routes/api/voice/status'
import { Route as ApiVoiceTransferRouteImport } from './routes/api/voice/transfer'
import { Route as ApiWebhooksMetaRouteImport } from './routes/api/webhooks/meta'
import { Route as ApiWidgetSlugRouteImport } from './routes/api/widget/$slug'
import { Route as AppPipelineInvoicesRouteImport } from './routes/app/pipeline.invoices'
import { Route as AppReceptionIndexRouteImport } from './routes/app/reception.index'
import { Route as AppReceptionCallsRouteImport } from './routes/app/reception.calls'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const HowRoute = HowRouteImport.update({
  id: '/how',
  path: '/how',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Verify2faRoute = Verify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubsRoute = AdminSubsRouteImport.update({
  id: '/subs',
  path: '/subs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppComputerRoute = AppComputerRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectRoute = AppConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AppRoute,
} as any)
const AppFirmRoute = AppFirmRouteImport.update({
  id: '/firm',
  path: '/firm',
  getParentRoute: () => AppRoute,
} as any)
const AppHireRoute = AppHireRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeRoute = AppKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppReachRoute = AppReachRouteImport.update({
  id: '/reach',
  path: '/reach',
  getParentRoute: () => AppRoute,
} as any)
const AppReceptionRoute = AppReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewRoute = AppReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const BookSlugRoute = BookSlugRouteImport.update({
  id: '/book/$slug',
  path: '/book/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewPageRoute = PreviewPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => PreviewRoute,
} as any)
const SignQuoteIdRoute = SignQuoteIdRouteImport.update({
  id: '/sign/$quoteId',
  path: '/sign/$quoteId',
  getParentRoute: () => rootRouteImport,
} as any)
const WSlugRoute = WSlugRouteImport.update({
  id: '/w/$slug',
  path: '/w/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComputerTickRoute = ApiComputerTickRouteImport.update({
  id: '/api/computer/tick',
  path: '/api/computer/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSmsInboundRoute = ApiSmsInboundRouteImport.update({
  id: '/api/sms/inbound',
  path: '/api/sms/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceGatherRoute = ApiVoiceGatherRouteImport.update({
  id: '/api/voice/gather',
  path: '/api/voice/gather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceHoldRoute = ApiVoiceHoldRouteImport.update({
  id: '/api/voice/hold',
  path: '/api/voice/hold',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceInboundRoute = ApiVoiceInboundRouteImport.update({
  id: '/api/voice/inbound',
  path: '/api/voice/inbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSampleRoute = ApiVoiceSampleRouteImport.update({
  id: '/api/voice/sample',
  path: '/api/voice/sample',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceStatusRoute = ApiVoiceStatusRouteImport.update({
  id: '/api/voice/status',
  path: '/api/voice/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTransferRoute = ApiVoiceTransferRouteImport.update({
  id: '/api/voice/transfer',
  path: '/api/voice/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMetaRoute = ApiWebhooksMetaRouteImport.update({
  id: '/api/webhooks/meta',
  path: '/api/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetSlugRoute = ApiWidgetSlugRouteImport.update({
  id: '/api/widget/$slug',
  path: '/api/widget/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPipelineInvoicesRoute = AppPipelineInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppPipelineRoute,
} as any)
const AppReceptionIndexRoute = AppReceptionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppReceptionRoute,
} as any)
const AppReceptionCallsRoute = AppReceptionCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppReceptionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/preview': typeof PreviewRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subs': typeof AdminSubsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/computer': typeof AppComputerRoute
  '/app/connect': typeof AppConnectRoute
  '/app/firm': typeof AppFirmRoute
  '/app/hire': typeof AppHireRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pipeline': typeof AppPipelineRouteWithChildren
  '/app/reach': typeof AppReachRoute
  '/app/reception': typeof AppReceptionRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/book/$slug': typeof BookSlugRoute
  '/preview/$page': typeof PreviewPageRoute
  '/sign/$quoteId': typeof SignQuoteIdRoute
  '/w/$slug': typeof WSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/computer/tick': typeof ApiComputerTickRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/voice/gather': typeof ApiVoiceGatherRoute
  '/api/voice/hold': typeof ApiVoiceHoldRoute
  '/api/voice/inbound': typeof ApiVoiceInboundRoute
  '/api/voice/sample': typeof ApiVoiceSampleRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transfer': typeof ApiVoiceTransferRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRoute
  '/api/widget/$slug': typeof ApiWidgetSlugRoute
  '/app/pipeline/invoices': typeof AppPipelineInvoicesRoute
  '/app/reception/calls': typeof AppReceptionCallsRoute
  '/app/reception/': typeof AppReceptionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/preview': typeof PreviewRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subs': typeof AdminSubsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/computer': typeof AppComputerRoute
  '/app/connect': typeof AppConnectRoute
  '/app/firm': typeof AppFirmRoute
  '/app/hire': typeof AppHireRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pipeline': typeof AppPipelineRouteWithChildren
  '/app/reach': typeof AppReachRoute
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/book/$slug': typeof BookSlugRoute
  '/preview/$page': typeof PreviewPageRoute
  '/sign/$quoteId': typeof SignQuoteIdRoute
  '/w/$slug': typeof WSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/computer/tick': typeof ApiComputerTickRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/voice/gather': typeof ApiVoiceGatherRoute
  '/api/voice/hold': typeof ApiVoiceHoldRoute
  '/api/voice/inbound': typeof ApiVoiceInboundRoute
  '/api/voice/sample': typeof ApiVoiceSampleRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transfer': typeof ApiVoiceTransferRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRoute
  '/api/widget/$slug': typeof ApiWidgetSlugRoute
  '/app/pipeline/invoices': typeof AppPipelineInvoicesRoute
  '/app/reception/calls': typeof AppReceptionCallsRoute
  '/app/reception': typeof AppReceptionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/how': typeof HowRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/preview': typeof PreviewRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-2fa': typeof Verify2faRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/subs': typeof AdminSubsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/computer': typeof AppComputerRoute
  '/app/connect': typeof AppConnectRoute
  '/app/firm': typeof AppFirmRoute
  '/app/hire': typeof AppHireRoute
  '/app/inbox': typeof AppInboxRoute
  '/app/knowledge': typeof AppKnowledgeRoute
  '/app/pipeline': typeof AppPipelineRouteWithChildren
  '/app/reach': typeof AppReachRoute
  '/app/reception': typeof AppReceptionRouteWithChildren
  '/app/review': typeof AppReviewRoute
  '/app/settings': typeof AppSettingsRoute
  '/book/$slug': typeof BookSlugRoute
  '/preview/$page': typeof PreviewPageRoute
  '/sign/$quoteId': typeof SignQuoteIdRoute
  '/w/$slug': typeof WSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/computer/tick': typeof ApiComputerTickRoute
  '/api/sms/inbound': typeof ApiSmsInboundRoute
  '/api/voice/gather': typeof ApiVoiceGatherRoute
  '/api/voice/hold': typeof ApiVoiceHoldRoute
  '/api/voice/inbound': typeof ApiVoiceInboundRoute
  '/api/voice/sample': typeof ApiVoiceSampleRoute
  '/api/voice/status': typeof ApiVoiceStatusRoute
  '/api/voice/transfer': typeof ApiVoiceTransferRoute
  '/api/webhooks/meta': typeof ApiWebhooksMetaRoute
  '/api/widget/$slug': typeof ApiWidgetSlugRoute
  '/app/pipeline/invoices': typeof AppPipelineInvoicesRoute
  '/app/reception/calls': typeof AppReceptionCallsRoute
  '/app/reception/': typeof AppReceptionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/how'
    | '/login'
    | '/onboard'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verify-2fa'
    | '/admin/content'
    | '/admin/login'
    | '/admin/subs'
    | '/admin/tickets'
    | '/app/calendar'
    | '/app/computer'
    | '/app/connect'
    | '/app/firm'
    | '/app/hire'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/pipeline'
    | '/app/reach'
    | '/app/reception'
    | '/app/review'
    | '/app/settings'
    | '/book/$slug'
    | '/preview/$page'
    | '/sign/$quoteId'
    | '/w/$slug'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/api/computer/tick'
    | '/api/sms/inbound'
    | '/api/voice/gather'
    | '/api/voice/hold'
    | '/api/voice/inbound'
    | '/api/voice/sample'
    | '/api/voice/status'
    | '/api/voice/transfer'
    | '/api/webhooks/meta'
    | '/api/widget/$slug'
    | '/app/pipeline/invoices'
    | '/app/reception/calls'
    | '/app/reception/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how'
    | '/login'
    | '/onboard'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verify-2fa'
    | '/admin/content'
    | '/admin/login'
    | '/admin/subs'
    | '/admin/tickets'
    | '/app/calendar'
    | '/app/computer'
    | '/app/connect'
    | '/app/firm'
    | '/app/hire'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/pipeline'
    | '/app/reach'
    | '/app/review'
    | '/app/settings'
    | '/book/$slug'
    | '/preview/$page'
    | '/sign/$quoteId'
    | '/w/$slug'
    | '/admin'
    | '/app'
    | '/api/auth/$'
    | '/api/computer/tick'
    | '/api/sms/inbound'
    | '/api/voice/gather'
    | '/api/voice/hold'
    | '/api/voice/inbound'
    | '/api/voice/sample'
    | '/api/voice/status'
    | '/api/voice/transfer'
    | '/api/webhooks/meta'
    | '/api/widget/$slug'
    | '/app/pipeline/invoices'
    | '/app/reception/calls'
    | '/app/reception'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/how'
    | '/login'
    | '/onboard'
    | '/preview'
    | '/pricing'
    | '/privacy'
    | '/signup'
    | '/terms'
    | '/verify-2fa'
    | '/admin/content'
    | '/admin/login'
    | '/admin/subs'
    | '/admin/tickets'
    | '/app/calendar'
    | '/app/computer'
    | '/app/connect'
    | '/app/firm'
    | '/app/hire'
    | '/app/inbox'
    | '/app/knowledge'
    | '/app/pipeline'
    | '/app/reach'
    | '/app/reception'
    | '/app/review'
    | '/app/settings'
    | '/book/$slug'
    | '/preview/$page'
    | '/sign/$quoteId'
    | '/w/$slug'
    | '/admin/'
    | '/app/'
    | '/api/auth/$'
    | '/api/computer/tick'
    | '/api/sms/inbound'
    | '/api/voice/gather'
    | '/api/voice/hold'
    | '/api/voice/inbound'
    | '/api/voice/sample'
    | '/api/voice/status'
    | '/api/voice/transfer'
    | '/api/webhooks/meta'
    | '/api/widget/$slug'
    | '/app/pipeline/invoices'
    | '/app/reception/calls'
    | '/app/reception/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  HowRoute: typeof HowRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  PreviewRoute: typeof PreviewRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  Verify2faRoute: typeof Verify2faRoute
  BookSlugRoute: typeof BookSlugRoute
  SignQuoteIdRoute: typeof SignQuoteIdRoute
  WSlugRoute: typeof WSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiComputerTickRoute: typeof ApiComputerTickRoute
  ApiSmsInboundRoute: typeof ApiSmsInboundRoute
  ApiVoiceGatherRoute: typeof ApiVoiceGatherRoute
  ApiVoiceHoldRoute: typeof ApiVoiceHoldRoute
  ApiVoiceInboundRoute: typeof ApiVoiceInboundRoute
  ApiVoiceSampleRoute: typeof ApiVoiceSampleRoute
  ApiVoiceStatusRoute: typeof ApiVoiceStatusRoute
  ApiVoiceTransferRoute: typeof ApiVoiceTransferRoute
  ApiWebhooksMetaRoute: typeof ApiWebhooksMetaRoute
  ApiWidgetSlugRoute: typeof ApiWidgetSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how': {
      id: '/how'
      path: '/how'
      fullPath: '/how'
      preLoaderRoute: typeof HowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-2fa': {
      id: '/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof Verify2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subs': {
      id: '/admin/subs'
      path: '/subs'
      fullPath: '/admin/subs'
      preLoaderRoute: typeof AdminSubsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/computer': {
      id: '/app/computer'
      path: '/computer'
      fullPath: '/app/computer'
      preLoaderRoute: typeof AppComputerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/connect': {
      id: '/app/connect'
      path: '/connect'
      fullPath: '/app/connect'
      preLoaderRoute: typeof AppConnectRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/firm': {
      id: '/app/firm'
      path: '/firm'
      fullPath: '/app/firm'
      preLoaderRoute: typeof AppFirmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hire': {
      id: '/app/hire'
      path: '/hire'
      fullPath: '/app/hire'
      preLoaderRoute: typeof AppHireRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbox': {
      id: '/app/inbox'
      path: '/inbox'
      fullPath: '/app/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/knowledge': {
      id: '/app/knowledge'
      path: '/knowledge'
      fullPath: '/app/knowledge'
      preLoaderRoute: typeof AppKnowledgeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pipeline': {
      id: '/app/pipeline'
      path: '/pipeline'
      fullPath: '/app/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reach': {
      id: '/app/reach'
      path: '/reach'
      fullPath: '/app/reach'
      preLoaderRoute: typeof AppReachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reception': {
      id: '/app/reception'
      path: '/reception'
      fullPath: '/app/reception'
      preLoaderRoute: typeof AppReceptionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/review': {
      id: '/app/review'
      path: '/review'
      fullPath: '/app/review'
      preLoaderRoute: typeof AppReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/book/$slug': {
      id: '/book/$slug'
      path: '/book/$slug'
      fullPath: '/book/$slug'
      preLoaderRoute: typeof BookSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$page': {
      id: '/preview/$page'
      path: '/$page'
      fullPath: '/preview/$page'
      preLoaderRoute: typeof PreviewPageRouteImport
      parentRoute: typeof PreviewRoute
    }
    '/sign/$quoteId': {
      id: '/sign/$quoteId'
      path: '/sign/$quoteId'
      fullPath: '/sign/$quoteId'
      preLoaderRoute: typeof SignQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$slug': {
      id: '/w/$slug'
      path: '/w/$slug'
      fullPath: '/w/$slug'
      preLoaderRoute: typeof WSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/computer/tick': {
      id: '/api/computer/tick'
      path: '/api/computer/tick'
      fullPath: '/api/computer/tick'
      preLoaderRoute: typeof ApiComputerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sms/inbound': {
      id: '/api/sms/inbound'
      path: '/api/sms/inbound'
      fullPath: '/api/sms/inbound'
      preLoaderRoute: typeof ApiSmsInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/gather': {
      id: '/api/voice/gather'
      path: '/api/voice/gather'
      fullPath: '/api/voice/gather'
      preLoaderRoute: typeof ApiVoiceGatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/hold': {
      id: '/api/voice/hold'
      path: '/api/voice/hold'
      fullPath: '/api/voice/hold'
      preLoaderRoute: typeof ApiVoiceHoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/inbound': {
      id: '/api/voice/inbound'
      path: '/api/voice/inbound'
      fullPath: '/api/voice/inbound'
      preLoaderRoute: typeof ApiVoiceInboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/sample': {
      id: '/api/voice/sample'
      path: '/api/voice/sample'
      fullPath: '/api/voice/sample'
      preLoaderRoute: typeof ApiVoiceSampleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/status': {
      id: '/api/voice/status'
      path: '/api/voice/status'
      fullPath: '/api/voice/status'
      preLoaderRoute: typeof ApiVoiceStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transfer': {
      id: '/api/voice/transfer'
      path: '/api/voice/transfer'
      fullPath: '/api/voice/transfer'
      preLoaderRoute: typeof ApiVoiceTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/meta': {
      id: '/api/webhooks/meta'
      path: '/api/webhooks/meta'
      fullPath: '/api/webhooks/meta'
      preLoaderRoute: typeof ApiWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widget/$slug': {
      id: '/api/widget/$slug'
      path: '/api/widget/$slug'
      fullPath: '/api/widget/$slug'
      preLoaderRoute: typeof ApiWidgetSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pipeline/invoices': {
      id: '/app/pipeline/invoices'
      path: '/invoices'
      fullPath: '/app/pipeline/invoices'
      preLoaderRoute: typeof AppPipelineInvoicesRouteImport
      parentRoute: typeof AppPipelineRoute
    }
    '/app/reception/': {
      id: '/app/reception/'
      path: '/'
      fullPath: '/app/reception/'
      preLoaderRoute: typeof AppReceptionIndexRouteImport
      parentRoute: typeof AppReceptionRoute
    }
    '/app/reception/calls': {
      id: '/app/reception/calls'
      path: '/calls'
      fullPath: '/app/reception/calls'
      preLoaderRoute: typeof AppReceptionCallsRouteImport
      parentRoute: typeof AppReceptionRoute
    }
  }
}

interface AdminRouteChildren {
  AdminContentRoute: typeof AdminContentRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSubsRoute: typeof AdminSubsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContentRoute: AdminContentRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSubsRoute: AdminSubsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppPipelineRouteChildren {
  AppPipelineInvoicesRoute: typeof AppPipelineInvoicesRoute
}

const AppPipelineRouteChildren: AppPipelineRouteChildren = {
  AppPipelineInvoicesRoute: AppPipelineInvoicesRoute,
}

const AppPipelineRouteWithChildren = AppPipelineRoute._addFileChildren(
  AppPipelineRouteChildren,
)

interface AppReceptionRouteChildren {
  AppReceptionCallsRoute: typeof AppReceptionCallsRoute
  AppReceptionIndexRoute: typeof AppReceptionIndexRoute
}

const AppReceptionRouteChildren: AppReceptionRouteChildren = {
  AppReceptionCallsRoute: AppReceptionCallsRoute,
  AppReceptionIndexRoute: AppReceptionIndexRoute,
}

const AppReceptionRouteWithChildren = AppReceptionRoute._addFileChildren(
  AppReceptionRouteChildren,
)

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppComputerRoute: typeof AppComputerRoute
  AppConnectRoute: typeof AppConnectRoute
  AppFirmRoute: typeof AppFirmRoute
  AppHireRoute: typeof AppHireRoute
  AppInboxRoute: typeof AppInboxRoute
  AppKnowledgeRoute: typeof AppKnowledgeRoute
  AppPipelineRoute: typeof AppPipelineRouteWithChildren
  AppReachRoute: typeof AppReachRoute
  AppReceptionRoute: typeof AppReceptionRouteWithChildren
  AppReviewRoute: typeof AppReviewRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppComputerRoute: AppComputerRoute,
  AppConnectRoute: AppConnectRoute,
  AppFirmRoute: AppFirmRoute,
  AppHireRoute: AppHireRoute,
  AppInboxRoute: AppInboxRoute,
  AppKnowledgeRoute: AppKnowledgeRoute,
  AppPipelineRoute: AppPipelineRouteWithChildren,
  AppReachRoute: AppReachRoute,
  AppReceptionRoute: AppReceptionRouteWithChildren,
  AppReviewRoute: AppReviewRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PreviewRouteChildren {
  PreviewPageRoute: typeof PreviewPageRoute
}

const PreviewRouteChildren: PreviewRouteChildren = {
  PreviewPageRoute: PreviewPageRoute,
}

const PreviewRouteWithChildren =
  PreviewRoute._addFileChildren(PreviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  HowRoute: HowRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  PreviewRoute: PreviewRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  Verify2faRoute: Verify2faRoute,
  BookSlugRoute: BookSlugRoute,
  SignQuoteIdRoute: SignQuoteIdRoute,
  WSlugRoute: WSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiComputerTickRoute: ApiComputerTickRoute,
  ApiSmsInboundRoute: ApiSmsInboundRoute,
  ApiVoiceGatherRoute: ApiVoiceGatherRoute,
  ApiVoiceHoldRoute: ApiVoiceHoldRoute,
  ApiVoiceInboundRoute: ApiVoiceInboundRoute,
  ApiVoiceSampleRoute: ApiVoiceSampleRoute,
  ApiVoiceStatusRoute: ApiVoiceStatusRoute,
  ApiVoiceTransferRoute: ApiVoiceTransferRoute,
  ApiWebhooksMetaRoute: ApiWebhooksMetaRoute,
  ApiWidgetSlugRoute: ApiWidgetSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
